apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-server
  name: grpc-server
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: grpc-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-server
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-server
  template:
    metadata:
      labels:
        service: grpc-server
    spec:
      containers:
      - image: ahmednoureldeen/grpc_server:latest
        name: grpc-server
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
